apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app
  namespace: argocd  # Ensure this matches where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/iemkamran/gitops-app.git
    path: environment/dev
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true