apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd  # Namespace where Argo CD is installed
spec:
  project: default
  source:
    repoURL: https://github.com/iemkamran/monitoring-stack-k8s.git
    path: prometheus-helm
    targetRevision: HEAD
    helm:
      releaseName: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
